In [5]:
import numpy as np

# Create numpy array from list
list = [1, 2, 3, 4, 5]
array = np.array(list)

# Multi dimensional array
nd_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


# What's the shape
print nd_array.shape

(2, 4)


In [6]:
# Zeros - return array of zeros default 
# floating type
zeros = np.zeros((2, 2))

# Same for ones
ones = np.ones((2, 2))

# Identity matrix
i = np.eye(5)
print i

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [7]:
# Gets evenly spaced numbers
# params = [start incl, stop excl, step]
lis = np.arange(1, 2, 0.5)
print lis

[ 1.   1.5]


## Arithmetic Operations

In [8]:
from __future__ import division
# Element wise multiplication
# [a1 a2 a3] * [b1 b2 b3] = [a1*b1 a2*b2 a3*b3]
# Same foe nd case
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])
print "Multiplication"
print a*b

# Exponential operation
print "Exponentiation"
n = a**2
print n

# Same for division
print "Divison" 
print a/b

# Same for Subtraction
print "Subtraction"
print a - b

# Addition
print "Addition"
print a + b

Multiplication
[ 4 10 18 28]
Exponentiation
[ 1  4  9 16]
Divison
[ 0.25        0.4         0.5         0.57142857]
Subtraction
[-3 -3 -3 -3]
Addition
[ 5  7  9 11]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# print arr[0:5]

# Modify from certain point to certain point
arr[0:5] = 100
# print arr

# Slice array
# Warning: this is shallow copy
# changing slice will change the original 
# array
slice = arr[0:5]
# print slice

# create deep copy, now changing slice
# won't change the original array
arr_copy = arr.copy()
# print arr_copy

# Indexing 2D array
# array[start_row:end_row , start_col:end_col]
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print arr_2d[:2, 1:]  # top right corner

# arr[:][1] doesn't work because
# arr[:] selects the entire array and
# arr[:][1] selects second column

# This sets the entire first row to 2
# similar to arr[0][:3] = 2
arr_2d[0] = 2
# print arr_2d


# arr[list_of_rows] will select list_of_rows
# in the order in the list
list_of_rows = [0, 1, 2]
print arr_2d[list_of_rows]  # prints 0th 1st 
                            # and 2nd column

[[2 2 2]
 [4 5 6]
 [7 8 9]]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# print arr[0:5]

# Modify from certain point to certain point
arr[0:5] = 100
# print arr

# Slice array
# Warning: this is shallow copy
# changing slice will change the original 
# array
slice = arr[0:5]
# print slice

# create deep copy, now changing slice
# won't change the original array
arr_copy = arr.copy()
# print arr_copy

# Indexing 2D array
# array[start_row:end_row , start_col:end_col]
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print arr_2d[:2, 1:]  # top right corner

# arr[:][1] doesn't work because
# arr[:] selects the entire array and
# arr[:][1] selects second column

# This sets the entire first row to 2
# similar to arr[0][:3] = 2
arr_2d[0] = 2
# print arr_2d


# arr[list_of_rows] will select list_of_rows
# in the order in the list
list_of_rows = [0, 1, 2]
print arr_2d[list_of_rows]  # prints 0th 1st 
                            # and 2nd column

[[2 2 2]
 [4 5 6]
 [7 8 9]]


In [11]:
# Reshape 1D array to x by y using reshape
arr = np.arange(30)
# print arr
arr = arr.reshape((6, 5))
# print arr

# Transpose
arr = arr.T
# print arr

# Dot product - Matrix multiplication
arr = arr.dot(arr.T)
# print arr

arr = np.array([[1, 2, 3], [4, 5, 6]])
print arr

print arr.swapaxes(0, 1)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [12]:
# Reshape 1D array to x by y using reshape
arr = np.arange(30)
# print arr
arr = arr.reshape((6, 5))
# print arr

# Transpose
arr = arr.T
# print arr

# Dot product - Matrix multiplication
arr = arr.dot(arr.T)
# print arr

arr = np.array([[1, 2, 3], [4, 5, 6]])
print arr

print arr.swapaxes(0, 1)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Universal Array Functions

In [13]:
arr = np.arange(11)
# square root
np.sqrt(arr)

# exp
np.exp(arr)

# return max entries of two arrays
# at each position
np.maximum(np.array([12, 2, 3, 4]), np.array([6, 7, 8, 9]))

array([12,  7,  8,  9])

In [13]:
import matplotlib.pyplot as plt
%matplotlib inline

points = np.arange(-5, 5, 0.01)

# meshgrid creates rangoli points out of
# the unique co ordinates you pass it in
dx, dy = np.meshgrid(points, points)

# imshow will show you colored form of the 
# matrix you have
z = (np.sin(dx) + np.sin(dy))
plt.imshow(np.sin(dx) + np.sin(dy))
plt.show()

## Array Processing

In [15]:
# numpy where
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
conditions = np.array([True, True, False, False])
ans = [(a_v if cond else b_v) for a_v, b_v, cond in zip(a, b, conditions)]
# print ans
# what numpy where does is exactly same as the
# above list comprehension
ans2 = np.where(conditions, a, b)
# print ans2

# Example : generate random 0 or 1 array
arr = np.random.randn(5, 5)  # 5x5 random array
print arr
# format (condition, if - do, else - do)
np.where(arr < 0, 0, 1)

[[-0.0943546  -0.2826438  -1.14367498  0.1476079  -1.31040367]
 [-0.68851269  0.98567149  0.65272481 -0.46577697 -0.96674932]
 [-0.60497777 -0.85458204  0.3178462   0.7396049   1.52535902]
 [-0.45979721  0.07584698 -1.30629667  1.20744855  1.40295374]
 [ 1.49428875 -1.69295824 -0.58141437 -1.86892962  0.14790705]]


array([[0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1],
       [1, 0, 0, 0, 1]])

## Some Handy Functions

In [16]:
arr = np.array([[13, 2, 3], [44, 53, 63], [7, 8, 9]])
arr.sum()   # sum of all values
print arr
arr.sum(0)  # sum along 0 axis - columns
arr.sum(1)  # sum along 1 axis - rows
arr.mean()  # mean
arr.std()   # std deviation
arr.var()   # variance

arr_1d = np.array([7, 43, 8, 5, 3])
arr_1d.sort()   # sorts 1D array normally

print arr_1d    
arr.sort()      # for 2D array, sorts each
print arr       # internal 1D array in order

arr_u = np.array([1, 2, 3, 4, 4, 5, 5])
np.unique(arr_u)    # returns unique values
# in1D is like are elements of list_a in list_b
# if yes return true else return false
np.in1d(arr_u, [2, 3, 4])

[[13  2  3]
 [44 53 63]
 [ 7  8  9]]
[ 3  5  7  8 43]
[[ 2  3 13]
 [44 53 63]
 [ 7  8  9]]


array([False,  True,  True,  True,  True, False, False], dtype=bool)

## Array Input and Output

In [17]:
arr = np.arange(10)
arr
np.save('my_array', arr)
arr = 10
# same like pickle
arr_npy = np.load('my_array.npy')  

arr2 = np.array([1, 2, 3, 4, 5])
# save as zip file 
# 2nd parameter is the name
# you want to give eg. a=arr1, later on
# when you fetch the zip file, you specify
# it like zip_file['a']
# can save multiple arrays like a=arr1, b=arr2
# and so on
np.savez('arr2', p=arr2)
zip_array = np.load('arr2.npz')
zip_array['p']

# save a single array to text file
arr_txt = np.array([[1, 2, 3], [4, 5, 6]])
arr_txt
np.savetxt('arr_txt.txt', arr_txt, delimiter=',')
from_txt = np.loadtxt('arr_txt.txt', delimiter=',')
from_txt

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])